### ISSUE TITLE
inactive tabs look disabled

### ISSUE THREAD

**Issue by eddywashere** [rackerlabs/canon-bootstrap#50]
![image](https://cloud.githubusercontent.com/assets/399776/5446859/9b4f339e-8479-11e4-8d5b-08c81ab5ca58.png)

**Comment by eddywashere** [comment]
@araiford until some entity truly owns canon and the process, I strongly feel that we should stick to canon spec, until that spec is formally updated. And that we should accept updates that reach parity with canon proper.

**Comment by araiford** [comment]
@eddywashere - I agree.

On a similar note - new patterns are fine when they are warranted.  We don't want to halt innovation.  Staying within the guidelines of Canon's current visual language is recommended so that we are aligned when more overarching changes come down the pipe.

**Comment by eddywashere** [comment]
+1
