### ISSUE TITLE
Missing login button

### ISSUE THREAD

**Issue by ksheedlo** [rackerlabs/canon-bootstrap#62]
http://rackerlabs.github.io/canon/ui-components/#buttons

The primary, secondary and link button types are all straightforwardly portable from Bootstrap, but the login button is not. I propose adding a `.btn-login` class.

**Comment by cbfx** [comment]
@ksheedlo It's just a red button, yeah? what about `.btn-danger`? http://getbootstrap.com/css/#buttons

**Comment by eddywashere** [comment]
I think it's a nice to have that we should very much consider. Going from canon to canon-bootstrap should be as smooth as possible. Maybe that includes having fallback classes where possible. On the flip side, making that transition is already a big breaking change for anyone's app. Keeping those classes could hold us back. Maybe.

**Comment by ksheedlo** [comment]
@cbfx `.btn-danger` is semantically different from `.rs-btn-login`. In Bootstrap, you use `.btn-danger` as a warning for potentially destructive actions, etc. Canon doesn't use red buttons that way. I think using `.btn-danger` is unsemantic and probably the wrong approach.

Here's one possible upgrade path:

- Add `.btn-login` as the recommended login button class going forward. Also add `.rs-btn-login` for the upgrade path from canon.
- Immediately deprecate `.btn-danger` and `.rs-btn-login`.
- Eventually drop support for `.rs-btn-login`, as well as `.btn-danger` if it can be done without breaking Bootstrap.

**Comment by bradgignac** [comment]
I actually disagree that we need fallbacks. Until we have someone who's actually migrating and wants to discuss their migration strategy, we shouldn't mess around with those. Depending on how its handled, it will make it harder.

**Comment by bradgignac** [comment]
Also, .btn-danger shouldn't be deprecated. It just shouldn't be used for login buttons because it isn't semantic. Part of the motivation for moving to Bootstrap was to break away from some areas in which Canon was over-prescriptive. The "only login buttons are red" issue is a perfectly example. That was how a design team that is no longer at Rackspace intended them to be used three years ago, but there are plenty of teams who are using red buttons for destructive actions.

**Comment by bradgignac** [comment]
@ksheedlo Please submit a PR for `.btn-login`.

**Comment by ksheedlo** [comment]
@bradgignac +1, thanks for the insight! I will send the PR as soon as I have time to get it written. Might not be till Friday, since I'm at rax.io.

**Comment by eddywashere** [comment]
closed by #63
