### ISSUE TITLE
Storing `build` directory in repo

### ISSUE THREAD

**Issue by bighappyface** [rackerlabs/canon-bootstrap#67]
From *CONTRIBUTING.md*:

> Do not commit changes to the build folder. These files are automatically generated and will be committed as part of the release process.

The `build` directory is stored in the repo though: https://github.com/rackerlabs/canon-bootstrap/tree/30bf45a6bcf87fddd43a918c033e9d4cd1fb9c3f/build

Is this point in *CONTRIBUTING.md* copy/paste or is this official policy? I agree that it shouldn't be stored and instead yielded automatically.

**Comment by bradgignac** [comment]
We commit built files as part of a release rather than with an individual PR.
